import Leftbar from '@/components/shared/Leftbar/Leftbar';
import '../globals.css';
import type { Metadata } from 'next';
import Rightbar from '@/components/shared/Rightbar/Rightbar';
import Bottombar from '@/components/shared/Bottombar/Bottombar';
import { Providers } from '@/redux/providers';

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body suppressHydrationWarning={true}>
        <Providers>
          <div id="container">
            <Leftbar />
            <div id="wrapper">{children}</div>
            <Rightbar />
          </div>
          <Bottombar />
        </Providers>
      </body>
    </html>
  );
}
