import '../globals.css';
import type { Metadata } from 'next';
import { Providers } from '@/redux/providers';
import Navbar from '@/components/shared/Navbar/Navbar';
import Footer from '@/components/shared/Footer/Footer';

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
