import { Providers } from '@/redux/providers';
import './globals.css';
import type { Metadata } from 'next';
import '@uploadthing/react/styles.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
    title: 'Threads',
    description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={poppins.className}>
            <body suppressHydrationWarning={true}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
