import { Providers } from '@/redux/providers';
import '../globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Threads',
    description: 'Generated by create next app',
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return children;
}
