import { Providers } from '@/redux/providers';
import '../globals.css';
import type { Metadata } from 'next';
import PublicRoute from '@/components/router/PublicRoute/PublicRoute';

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <PublicRoute>{children}</PublicRoute>;
  // return <>{children}</>;
}
